[package]
name = "rtsp-to-webrtc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
chrono = "0.4.22"
clap = "3.2.22"
env_logger = "0.9.1"
failure = "0.1.8"
futures = "0.3.24"
log = "0.4.17"
retina = "0.4.1"
rocket = "0.5.0-rc.2"
tokio = { version = "1.21.1", features = ["sync", "fs"] }
url = "2.3.1"
webrtc = "0.5.1"
